### ISSUE TITLE
[BUG] StartPage crashes Playnite when closing a game

### ISSUE THREAD

**Issue by BloodShed-Oni** [felixkmh/StartPage-for-Playnite#177]
After closing a game, there's a chance StartPage will crash Playnite with the error message:

"Extension "StartPage" caused an unrecoverable error."

It's seemingly random (it can happen only once with the same game, just somtimes or everytime).

Here's what I found in Playnite.log

```
12-11 19:13:30.132|ERROR|PlayniteApplication:Unhandled exception occured.
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at System.Windows.Data.CollectionViewSource.EnsureView()
   at System.Windows.Data.CollectionViewSource.DeferHelper.Dispose()
   at LandingPage.ViewModels.ShelveViewModel.<UpdateGamesAsync>d__53.MoveNext() in E:\Programmierung\playnite-dev\StartPage-for-Playnite\source\StartPage\ViewModels\ShelveViewModel.cs:line 473
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LandingPage.ViewModels.ShelvesViewModel.<UpdateShelvesAsync>d__49.MoveNext() in E:\Programmierung\playnite-dev\StartPage-for-Playnite\source\StartPage\ViewModels\ShelvesViewModel.cs:line 181
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LandingPage.ViewModels.ShelvesViewModel.<Games_ItemUpdatedAsync>d__50.MoveNext() in E:\Programmierung\playnite-dev\StartPage-for-Playnite\source\StartPage\ViewModels\ShelvesViewModel.cs:line 196
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
12-11 19:13:30.132|ERROR|PlayniteApplication:Unhandled exception occured.
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at System.Windows.Data.CollectionViewSource.EnsureView()
   at System.Windows.Data.CollectionViewSource.DeferHelper.Dispose()
   at LandingPage.ViewModels.ShelveViewModel.<UpdateGamesAsync>d__53.MoveNext() in E:\Programmierung\playnite-dev\StartPage-for-Playnite\source\StartPage\ViewModels\ShelveViewModel.cs:line 473
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LandingPage.ViewModels.ShelvesViewModel.<UpdateShelvesAsync>d__49.MoveNext() in E:\Programmierung\playnite-dev\StartPage-for-Playnite\source\StartPage\ViewModels\ShelvesViewModel.cs:line 181
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LandingPage.ViewModels.ShelvesViewModel.<Games_ItemUpdatedAsync>d__50.MoveNext() in E:\Programmierung\playnite-dev\StartPage-for-Playnite\source\StartPage\ViewModels\ShelvesViewModel.cs:line 196
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
12-11 19:13:30.361|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ExtensionCrashHandlerWindowFactory: dda37628-13d9-4400-800c-f9bc4654ea4b
12-11 19:13:30.453|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ExtensionCrashHandlerWindowFactory: 520528ab-263d-499b-b0b5-30801bc36c8b
```

**Comment by felixkmh** [comment]
Check if it still happens with v2.11.2

**Comment by BloodShed-Oni** [comment]
> Check if it still happens with v2.11.2

Looks like it's fixed.
