### ISSUE TITLE
[BUG] Extension "StartPage" failed to load properly

### ISSUE THREAD

**Issue by ivanlorusso** [felixkmh/StartPage-for-Playnite#202]
Hi, I'm receiving this error every time I start Playnite.

This is what I found in Playnite.log
`17-08 10:03:21.603|ERROR|ExtensionFactory:Failed to load plugin: StartPage
17-08 10:03:21.603|ERROR|ExtensionFactory:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Playnite.Plugins.ExtensionFactory.<LoadPlugins>d__33.MoveNext() in C:\projects\playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 451
   at Playnite.Plugins.ExtensionFactory.LoadPlugins(List``1 ignoreList, Boolean builtInOnly, List``1 externals) in C:\projects\playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 411
17-08 10:03:21.603|ERROR|ExtensionFactory:
System.IO.FileNotFoundException: Could not load file or assembly 'StartPage.SDK.Async, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'StartPage.SDK.Async, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'`

**Comment by felixkmh** [comment]
Hi, can you maybe include the portion of the log that lists all extensions being loaded? This way I can check whether it is due to some sort of incompatibility between extensions. You could also check whether 'StartPage.SDK.Async.dll' exists in StartPage's installation directory. If not, try re-installing it.

**Comment by ivanlorusso** [comment]
Sure, here it is:

```17-08 10:03:21.411|INFO |ExtensionFactory:Loaded plugin: AmazonGames library integration, version 2.6
17-08 10:03:21.411|INFO |ExtensionFactory:Loaded plugin: Battle.net library integration, version 2.12
17-08 10:03:21.411|INFO |ExtensionFactory:Loaded plugin: Bethesda library integration, version 2.2
17-08 10:03:21.428|INFO |ExtensionFactory:Loaded plugin: Emulation Toolbox, version 1.3.2
17-08 10:03:21.476|INFO |ExtensionFactory:Loaded plugin: Epic Store library integration, version 2.17
17-08 10:03:21.501|INFO |ExtensionFactory:Loaded plugin: Extra Metadata Loader, version 1.67
17-08 10:03:21.553|INFO |ExtensionFactory:Loaded plugin: DuplicateHider, version 3.14.5
17-08 10:03:21.585|INFO |ExtensionFactory:Loaded plugin: QuickSearch, version 2.24.6
17-08 10:03:21.603|ERROR|ExtensionFactory:Failed to load plugin: StartPage
17-08 10:03:21.603|ERROR|ExtensionFactory:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Playnite.Plugins.ExtensionFactory.<LoadPlugins>d__33.MoveNext() in C:\projects\playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 451
   at Playnite.Plugins.ExtensionFactory.LoadPlugins(List`1 ignoreList, Boolean builtInOnly, List`1 externals) in C:\projects\playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 411
17-08 10:03:21.603|ERROR|ExtensionFactory:
System.IO.FileNotFoundException: Could not load file or assembly 'StartPage.SDK.Async, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'StartPage.SDK.Async, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

17-08 10:03:21.603|ERROR|ExtensionFactory:
System.IO.FileNotFoundException: Could not load file or assembly 'StartPage.SDK.Async, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'StartPage.SDK.Async, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

17-08 10:03:21.603|ERROR|ExtensionFactory:
System.IO.FileNotFoundException: Could not load file or assembly 'StartPage.SDK.Async, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'StartPage.SDK.Async, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

17-08 10:03:21.603|ERROR|ExtensionFactory:
System.IO.FileNotFoundException: Could not load file or assembly 'StartPage.SDK.Async, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'StartPage.SDK.Async, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

17-08 10:03:21.603|ERROR|ExtensionFactory:
System.IO.FileNotFoundException: Could not load file or assembly 'StartPage.SDK.Async, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'StartPage.SDK.Async, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

17-08 10:03:21.603|ERROR|ExtensionFactory:
System.IO.FileNotFoundException: Could not load file or assembly 'StartPage.SDK.Async, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'StartPage.SDK.Async, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

17-08 10:03:21.603|ERROR|ExtensionFactory:
System.IO.FileNotFoundException: Could not load file or assembly 'StartPage.SDK.Async, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'StartPage.SDK.Async, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

17-08 10:03:21.629|INFO |ExtensionFactory:Loaded plugin: Games Size Calculator, version 1.29.1
17-08 10:03:21.638|INFO |ExtensionFactory:Loaded plugin: GOG library integration, version 2.17
17-08 10:03:21.648|INFO |ExtensionFactory:Loaded plugin: IGDB metadata provider, version 2.8
17-08 10:03:21.648|INFO |ExtensionFactory:Loaded plugin: Installation Status Updater, version 2.39
17-08 10:03:21.665|INFO |ExtensionFactory:Loaded plugin: EA app library integration, version 2.10
17-08 10:03:21.784|INFO |ExtensionFactory:Loaded plugin: GameActivity, version 3.1.0
17-08 10:03:21.859|INFO |ExtensionFactory:Loaded plugin: HowLongToBeat, version 3.1.2
17-08 10:03:21.942|INFO |ExtensionFactory:Loaded plugin: SuccessStory, version 3.1.3
17-08 10:03:22.135|INFO |ExtensionFactory:Loaded plugin: ThemeModifier, version 3.0
17-08 10:03:22.149|INFO |ExtensionFactory:Loaded plugin: PlayStation library integration, version 2.28
17-08 10:03:22.149|INFO |ExtensionFactory:Loaded plugin: SteamGridDB Metadata Provider, version 1.1
17-08 10:03:22.214|INFO |ExtensionFactory:Loaded plugin: Steam library integration, version 2.18
17-08 10:03:22.253|INFO |ExtensionFactory:Loaded plugin: Ubisoft Connect library integration, version 2.5
17-08 10:03:22.262|INFO |ExtensionFactory:Loaded plugin: Xbox library integration, version 2.11
17-08 10:03:22.764|INFO |ExtensionFactory:Loaded script extension: C:\Users\ivanl\AppData\Roaming\Playnite\Extensions\Game_Media_Processor\GameMediaProcessor.psm1, version 1.9.0
17-08 10:03:22.779|INFO |ExtensionFactory:Loaded script extension: C:\Users\ivanl\AppData\Roaming\Playnite\Extensions\Game_Media_Tools\GameMediaTools.psm1, version 2.10
17-08 10:03:22.801|INFO |ExtensionFactory:Loaded script extension: C:\Users\ivanl\AppData\Roaming\Playnite\Extensions\Image_Cache_Size_Saver\ImageCacheSizeSaver.psm1, version 2.12
17-08 10:03:22.810|INFO |ExtensionFactory:Loaded script extension: C:\Users\ivanl\AppData\Roaming\Playnite\Extensions\LibraryExporterPS_Builtin\LibraryExporter.psm1, version 2.0
17-08 10:03:22.831|INFO |ExtensionFactory:Loaded script extension: C:\Users\ivanl\AppData\Roaming\Playnite\Extensions\Links_Sorter\LinksSorter.psm1, version 2.6
17-08 10:03:22.841|INFO |ExtensionFactory:Loaded script extension: C:\Users\ivanl\AppData\Roaming\Playnite\Extensions\Nexus_Mods_Checker_ece2874c-be52-4a64-b178-ed379a042f85\NexusModsChecker.psm1, version 2.11```

**Comment by ivanlorusso** [comment]
I had the chance to check, the file was there, I don't know why it caused this issue. Reinstalling the extension fixed it though.

**Comment by ivanlorusso** [comment]
The solution was only temporary though, apparently the problem pops up again every time I restart my PC.

**Comment by veksha** [comment]
i have similar problem but different exception: JsonReaderException.

```
14-08 20:52:29.533|ERROR|ExtensionFactory:Failed to load plugin: StartPage

Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path 'ShowNotificationButtons', line 139, position 3.

   в Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   в Newtonsoft.Json.JsonTextReader.ParseProperty()
   в Newtonsoft.Json.JsonTextReader.ParseObject()
   в Newtonsoft.Json.JsonTextReader.Read()
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   в Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   в Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   в Playnite.Common.Serialization.FromJsonStream[T](Stream stream) в C:\projects\playnite\source\Playnite\Common\Serialization.cs:строка 343
   в Playnite.Common.Serialization.FromJsonFile[T](String filePath) в C:\projects\playnite\source\Playnite\Common\Serialization.cs:строка 394
   в Playnite.Common.DataSerializer.FromJsonFile[T](String filePath) в C:\projects\playnite\source\Playnite\Common\Serialization.cs:строка 90
   в Playnite.SDK.Data.Serialization.FromJsonFile[T](String filePath) в C:\projects\playnite\source\PlayniteSDK\Data\DataSerialization.cs:строка 478
   в Playnite.SDK.Plugins.Plugin.LoadPluginSettings[TSettings]() в C:\projects\playnite\source\PlayniteSDK\Plugins\Plugin.cs:строка 353
   в LandingPage.LandingPageSettingsViewModel..ctor(LandingPageExtension plugin) в E:\Programmierung\playnite-dev\StartPage-for-Playnite\source\StartPage\LandingPageSettings.cs:строка 285
   в LandingPage.LandingPageExtension..ctor(IPlayniteAPI api) в E:\Programmierung\playnite-dev\StartPage-for-Playnite\source\StartPage\LandingPageExtension.cs:строка 123

```

**Comment by veksha** [comment]
deleted corrupted `config.json` in `Playnite64\ExtensionsData\a6a3dcf6-9bfe-426c-afb0-9f49409ae0c5` folder.
now extension loads correctly.

BTW: this "Data folder" link wasn't working until I deleted corrupted config.json:

![image](https://github.com/user-attachments/assets/66da5eaf-602f-448e-ad52-752723ff35c8)
